### ISSUE TITLE
Add namespace in the usage of using an Executor when do `jina hub push`

### ISSUE THREAD

**Issue by mapleeit** [jina-ai/jina-hubble-sdk#107]

**Comment by delgermurun** [comment]
We are introducing new scheme/prefix `jinaai`.
We will support both `jinahub://` and `jinaai://` prefixes, but only document `jinaai://` one.

- [ ] Replace `jinahub` with `jinaai` for all public content. Usage message, docs etc...

**Comment by delgermurun** [comment]
For new format we need username for the URI.

For now, only the owner can push, but once organization support is added it will no longer be the case.
Also, in order to get the logged-in user's name, an additional request needs to be sent.

So, I think it would be better to include the owner's name in the API response.
What do you think @mapleeit @nomagick?

**Comment by nomagick** [comment]
Makes sense. As part of the meta.

**Comment by delgermurun** [comment]
Cool. So for now please add it into pushing stream's completed payload @nomagick 
Thanks.
